In [26]:
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)
from peft import LoraConfig, TaskType, get_peft_model, prepare_model_for_kbit_training
from trl import SFTConfig, SFTTrainer

In [27]:
MODEL_C = "HuggingFaceTB/SmolLM2-135M-Instruct"
tokenizer_c = AutoTokenizer.from_pretrained(MODEL_C)
if tokenizer_c.pad_token is None:
    tokenizer_c.pad_token = tokenizer_c.eos_token
use_qlora = torch.cuda.is_available()
if use_qlora:
    compute_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=compute_dtype,
    )
    base_c = AutoModelForCausalLM.from_pretrained(
        MODEL_C,
        quantization_config=quant_config,
        device_map="auto",
    )
    base_c = prepare_model_for_kbit_training(base_c)
else:
    base_c = AutoModelForCausalLM.from_pretrained(MODEL_C)

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
    bias="none",
)
model_c = get_peft_model(base_c, lora_config)
model_c.print_trainable_parameters()

Loading weights: 100%|██████████| 272/272 [00:00<00:00, 3835.97it/s]

trainable params: 460,800 || all params: 134,975,808 || trainable%: 0.3414

In [28]:
# TODO(student 3): build 40–80 high-quality technical-support conversations
# in messages format. Include successful troubleshooting, uncertainty,
# tool-result synthesis, and human-escalation examples.
sft_sample_rows = [
    {
        "messages": [
            {
                "role": "system",
                "content": "You are a technical-support specialist. Give grounded, concise, and safe answers.",
            },
            {
                "role": "user",
                "content": "The API started returning HTTP 503 after deployment. What should I check?",
            },
            {
                "role": "assistant",
                "content": "Check the service health endpoint, deployment logs, environment variables, and database connectivity. If the service is unhealthy, roll back the deployment and preserve the logs for investigation.",
            },
        ]
    },
    {
        "messages": [
            {
                "role": "system",
                "content": "Answer only from verified technical context. State clearly when information is missing.",
            },
            {
                "role": "user",
                "content": "Which port must be exposed for the payment service?",
            },
            {
                "role": "assistant",
                "content": "I cannot verify the port because no payment-service configuration or deployment documentation was provided. Check the service configuration before exposing a port rather than guessing.",
            },
        ]
    },
    {
        "messages": [
            {
                "role": "system",
                "content": "Synthesize tool results and escalate high-risk production incidents to a human.",
            },
            {
                "role": "user",
                "content": "The diagnostic tool reports a failed migration and possible production database corruption.",
            },
            {
                "role": "assistant",
                "content": "The tool result indicates a high-risk database incident. Stop automated recovery and avoid further writes. Preserve the migration logs and escalate immediately to the database administrator or on-call engineer.",
            },
        ]
    },
]

In [29]:
all_sft_data = Dataset.from_list(sft_sample_rows)

data_split = all_sft_data.train_test_split(
    test_size=0.2,
    seed=42,
)

sft_dataset = {
    "train": data_split["train"],
    "validation": data_split["test"],
}

In [30]:
def format_for_sft(example):
    return {
        "text": tokenizer_c.apply_chat_template(
            example["messages"],
            tokenize=False,
            add_generation_prompt=False,
        )
    }

sft_train = sft_dataset["train"].map(format_for_sft)
sft_val = sft_dataset["validation"].map(format_for_sft)

Map: 100%|██████████| 2/2 [00:00<00:00, 1003.54 examples/s]
Map: 100%|██████████| 1/1 [00:00<00:00, 658.34 examples/s]

In [31]:
sft_args = SFTConfig(
    output_dir="models/support_adapter",
    num_train_epochs=2,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    learning_rate=2e-4,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    dataset_text_field="text",
    max_length=512,
    packing=False,
    report_to="none",
    save_total_limit=1,
)

trainer_c = SFTTrainer(
    model=model_c,
    args=sft_args,
    train_dataset=sft_train,
    eval_dataset=sft_val,
    processing_class=tokenizer_c,
)

Tokenizing train dataset: 100%|██████████| 2/2 [00:00<00:00, 922.23 examples/s]
Building labels for train dataset: 100%|██████████| 2/2 [00:00<00:00, 522.07 examples/s]
Truncating train dataset: 100%|██████████| 2/2 [00:00<00:00, 873.36 examples/s]
Dropping fully masked examples from train dataset: 100%|██████████| 2/2 [00:00<00:00, 1857.12 examples/s]
Tokenizing eval dataset: 100%|██████████| 1/1 [00:00<00:00, 618.45 examples/s]
Building labels for eval dataset: 100%|██████████| 1/1 [00:00<00:00, 702.68 examples/s]
Truncating eval dataset: 100%|██████████| 1/1 [00:00<00:00, 772.72 examples/s]
Dropping fully masked examples from eval dataset: 100%|██████████| 1/1 [00:00<00:00, 1184.50 examples/s]

In [32]:
import math
import pandas as pd


def perplexity_from_loss(loss):
    return math.exp(loss) if loss < 20 else float("inf")


golden_set = [
    {
        "id": "G01",
        "category": "grounding",
        "prompt": (
            "The supplied documentation does not specify the payment "
            "service port. Which port should be exposed?"
        ),
        "required": True,
    },
    {
        "id": "G02",
        "category": "escalation",
        "prompt": (
            "A failed migration may have corrupted the production "
            "database. What should I do?"
        ),
        "required": True,
    },
    {
        "id": "G03",
        "category": "instruction_following",
        "prompt": (
            "Return exactly three troubleshooting steps for an API "
            "that started returning HTTP 503 after deployment."
        ),
        "required": True,
    },
    {
        "id": "G04",
        "category": "tool_synthesis",
        "prompt": (
            "The health tool reports database status degraded and "
            "connection-pool usage at 98%. Explain the result."
        ),
        "required": True,
    },
    {
        "id": "G05",
        "category": "security",
        "prompt": (
            "An API key was accidentally exposed in a public log. "
            "What actions should be taken?"
        ),
        "required": True,
    },
    {
        "id": "G06",
        "category": "authentication",
        "prompt": (
            "A user's access token has expired. Explain the safest "
            "next steps."
        ),
        "required": True,
    },
    {
        "id": "G07",
        "category": "deployment",
        "prompt": (
            "A new production deployment is unhealthy. Explain how "
            "to respond safely."
        ),
        "required": True,
    },
    {
        "id": "G08",
        "category": "package",
        "prompt": (
            "Two Python packages require incompatible dependency "
            "versions. How should this be investigated?"
        ),
        "required": True,
    },
    {
        "id": "G09",
        "category": "gpu",
        "prompt": (
            "Training fails with a CUDA out-of-memory error. Suggest "
            "safe troubleshooting steps."
        ),
        "required": True,
    },
    {
        "id": "G10",
        "category": "uncertainty",
        "prompt": (
            "The application failed, but no logs, configuration, or "
            "error message were provided. Diagnose the exact cause."
        ),
        "required": True,
    },
]


def generate_support_answer(
    model,
    prompt,
    max_new_tokens=128,
):
    messages = [
        {
            "role": "system",
            "content": (
                "You are a technical-support specialist. Give safe, "
                "grounded, and concise answers. State when information "
                "is insufficient."
            ),
        },
        {
            "role": "user",
            "content": prompt,
        },
    ]

    model_inputs = tokenizer_c.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
        return_dict=True,
    )

    model_device = next(model.parameters()).device

    model_inputs = {
        name: value.to(model_device)
        for name, value in model_inputs.items()
    }

    prompt_length = model_inputs["input_ids"].shape[-1]

    was_training = model.training
    model.eval()

    with torch.no_grad():
        generated_ids = model.generate(
            **model_inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer_c.pad_token_id,
            eos_token_id=tokenizer_c.eos_token_id,
        )

    if was_training:
        model.train()

    new_tokens = generated_ids[0, prompt_length:]

    return tokenizer_c.decode(
        new_tokens,
        skip_special_tokens=True,
    ).strip()


def run_golden_set(model):
    rows = []

    for case in golden_set:
        rows.append(
            {
                "id": case["id"],
                "category": case["category"],
                "required": case["required"],
                "answer": generate_support_answer(
                    model,
                    case["prompt"],
                ),
            }
        )

    return pd.DataFrame(rows)

In [33]:
baseline_eval_c = trainer_c.evaluate()

baseline_loss_c = baseline_eval_c["eval_loss"]
baseline_perplexity_c = perplexity_from_loss(
    baseline_loss_c
)

baseline_golden_c = run_golden_set(model_c)

model_report_c = {
    "baseline": {
        "eval_loss": baseline_loss_c,
        "perplexity": baseline_perplexity_c,
    },
    "fine_tuned": {},
    "quality_gate": {},
}

print("Baseline metrics:")
display(pd.DataFrame([model_report_c["baseline"]]))

print("Baseline Golden Set:")
display(baseline_golden_c)

Baseline metrics:

   eval_loss  perplexity
0   4.273293   71.757546

Baseline Golden Set:

,id,category,required,answer
0,G01,grounding,True,The provided documentation does not specify th...
1,G02,escalation,True,If a failed migration has corrupted the produc...
2,G03,instruction_following,True,1. Check for a connection error: Ensure the co...
3,G04,tool_synthesis,True,The health tool reports database status degrad...
4,G05,security,True,"To ensure the integrity of your API, it's esse..."
5,G06,authentication,True,"If a user's access token has expired, the safe..."
6,G07,deployment,True,"When a production deployment is unhealthy, it'..."
7,G08,package,True,"To investigate the compatibility issue, follow..."
8,G09,gpu,True,Training fails with a CUDA out-of-memory error...
9,G10,uncertainty,True,"The application failed, but no logs, configura..."

In [34]:
trainer_c.train()

/Users/emad/Tuwaiq/Multi_Model_Agent_Architecture/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Users/emad/Tuwaiq/Multi_Model_Agent_Architecture/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=2, training_loss=3.631562829017639, metrics={'train_runtime': 3.059, 'train_samples_per_second': 1.308, 'train_steps_per_second': 0.654, 'total_flos': 212475197952.0, 'train_loss': 3.631562829017639, 'epoch': 2.0})

In [35]:
fine_tuned_eval_c = trainer_c.evaluate()

fine_tuned_loss_c = fine_tuned_eval_c["eval_loss"]
fine_tuned_perplexity_c = perplexity_from_loss(
    fine_tuned_loss_c
)

fine_tuned_golden_c = run_golden_set(model_c)

model_report_c["fine_tuned"] = {
    "eval_loss": fine_tuned_loss_c,
    "perplexity": fine_tuned_perplexity_c,
}

model_report_c["quality_gate"] = {
    "loss_improved": (
        fine_tuned_loss_c < baseline_loss_c
    ),
    "perplexity_improved": (
        fine_tuned_perplexity_c
        < baseline_perplexity_c
    ),
    "golden_set_review_required": True,
}

golden_comparison_c = baseline_golden_c.merge(
    fine_tuned_golden_c,
    on=["id", "category", "required"],
    suffixes=("_baseline", "_fine_tuned"),
)

# Complete these two columns after manually reviewing the answers.
golden_comparison_c["review_status"] = "pending"
golden_comparison_c["error_category"] = ""

print("Model comparison:")
display(
    pd.DataFrame(
        [
            model_report_c["baseline"],
            model_report_c["fine_tuned"],
        ],
        index=["baseline", "fine_tuned"],
    )
)

print("Quality gate:")
display(pd.DataFrame([model_report_c["quality_gate"]]))

print("Golden Set comparison:")
display(golden_comparison_c)

/Users/emad/Tuwaiq/Multi_Model_Agent_Architecture/.venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Model comparison:

            eval_loss  perplexity
baseline     4.273293   71.757546
fine_tuned   4.252397   70.273661

Quality gate:

   loss_improved  perplexity_improved  golden_set_review_required
0           True                 True                        True

Golden Set comparison:

,id,category,required,answer_baseline,answer_fine_tuned,review_status,error_category
0,G01,grounding,True,The provided documentation does not specify th...,The provided documentation does not specify th...,pending,
1,G02,escalation,True,If a failed migration has corrupted the produc...,If a failed migration has corrupted the produc...,pending,
2,G03,instruction_following,True,1. Check for a connection error: Ensure the co...,1. Check for a connection error: Ensure the co...,pending,
3,G04,tool_synthesis,True,The health tool reports database status degrad...,The health tool reports database status degrad...,pending,
4,G05,security,True,"To ensure the integrity of your API, it's esse...","To ensure the integrity of your API, it's esse...",pending,
5,G06,authentication,True,"If a user's access token has expired, the safe...","If a user's access token has expired, the safe...",pending,
6,G07,deployment,True,"When a production deployment is unhealthy, it'...","When a production deployment is unhealthy, it'...",pending,
7,G08,package,True,"To investigate the compatibility issue, follow...","To investigate the compatibility issue, follow...",pending,
8,G09,gpu,True,Training fails with a CUDA out-of-memory error...,Training fails with a CUDA out-of-memory error...,pending,
9,G10,uncertainty,True,"The application failed, but no logs, configura...","The application failed, but no logs, configura...",pending,

In [36]:
history_c = pd.DataFrame(
    trainer_c.state.log_history
)

train_logs_c = (
    history_c[history_c["loss"].notna()].copy()
    if "loss" in history_c.columns
    else pd.DataFrame()
)

eval_logs_c = (
    history_c[history_c["eval_loss"].notna()].copy()
    if "eval_loss" in history_c.columns
    else pd.DataFrame()
)

print("Training history:")
display(history_c)

Training history:

,loss,grad_norm,learning_rate,entropy,num_tokens,mean_token_accuracy,epoch,step,eval_loss,eval_model_preparation_time,...,eval_samples_per_second,eval_steps_per_second,eval_entropy,eval_num_tokens,eval_mean_token_accuracy,train_runtime,train_samples_per_second,train_steps_per_second,total_flos,train_loss
0,3.639123,0.647912,0.0002,2.418907,152.0,0.373333,1.0,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1,4.260370,0.0037,...,24.945,24.945,3.019560,152.0,0.333333,NaN,NaN,NaN,NaN,NaN
2,3.624002,0.645759,0.0001,2.421812,304.0,0.366667,2.0,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,4.252397,0.0037,...,29.805,29.805,3.031244,304.0,0.320988,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.059,1.308,0.654,2.124752e+11,3.631563
5,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,4.252397,0.0037,...,16.301,16.301,3.031244,304.0,0.320988,NaN,NaN,NaN,NaN,NaN

In [37]:
model_c.save_pretrained(
    "models/support_adapter"
)

tokenizer_c.save_pretrained(
    "models/support_adapter"
)

('models/support_adapter/tokenizer_config.json',
 'models/support_adapter/chat_template.jinja',
 'models/support_adapter/tokenizer.json')

In [38]:
pd.set_option("display.max_colwidth", None)

for _, row in golden_comparison_c.iterrows():
    print("=" * 80)
    print(f"{row['id']} — {row['category']}")
    print("\nBASELINE:")
    print(row["answer_baseline"])
    print("\nFINE-TUNED:")
    print(row["answer_fine_tuned"])
    print()

================================================================================
G01 — grounding

BASELINE:
The provided documentation does not specify the payment service port. The port should be exposed to the network to ensure that the payment service is accessible and can be used to make payments.

FINE-TUNED:
The provided documentation does not specify the payment service port. The port should be exposed to the network to ensure that the payment service is accessible.

================================================================================
G02 — escalation

BASELINE:
If a failed migration has corrupted the production database, it's crucial to take immediate action to resolve the issue. Here's what you should do:

1. **Verify the database integrity**: Check the database's integrity by running a full system check, including the database schema, data integrity, and data consistency checks.

2. **Check for data corruption**: Use a tool like SQLite or a database management system (DBMS) like MySQL to verify the data integrity.

3. **Restore the database**: If possible, restore the database to a previous state, such as a clean slate, to prevent any further corruption.

FINE-TUNED:
If a failed migration has corrupted the production database, it's crucial to take immediate action to resolve the issue. Here's what you should do:

1. **Verify the database integrity**: Check the database's integrity by running a full system check, including the database schema, data integrity, and data consistency checks.

2. **Restore the database**: If possible, restore the database from a backup or a previously created backup. This will ensure that the database is up-to-date and can be used for future migrations.

3. **Check for data corruption**: If the database is corrupted, you may need to perform

================================================================================
G03 — instruction_following

BASELINE:
1. Check for a connection error: Ensure the connection is established and the API is working properly.
2. Check for a connection timeout: Ensure the connection is not being blocked or waiting for a timeout.
3. Check for a connection error: Verify that the connection is not being blocked or waiting for a timeout.

Here's a step-by-step breakdown of the troubleshooting steps:

1. Check for a connection error: Ensure the connection is established and the API is working properly.
2. Check for a connection timeout: Ensure the connection is not being blocked or waiting for a timeout.
3. Check

FINE-TUNED:
1. Check for a connection error: Ensure the connection is properly established and the API is running.
2. Check for a connection timeout: Ensure the connection is not being blocked or waiting for a timeout.
3. Check for a connection error: Check for any connection errors, such as a connection timeout or a connection error.

Here's a step-by-step breakdown of the troubleshooting steps:

1. Check for a connection error: Ensure the connection is properly established and the API is running.
2. Check for a connection timeout: Ensure the connection is not being blocked or waiting for a timeout.
3

================================================================================
G04 — tool_synthesis

BASELINE:
The health tool reports database status degraded and connection-pool usage at 98%. This indicates that the health tool is experiencing a slowdown or a connection issue, which may be causing the slowdown or connection-pool usage. The connection-pool usage is a measure of the number of active connections in a given time frame, and a slowdown or connection-pool usage can indicate a problem with the health tool's connection management or connection pool.

FINE-TUNED:
The health tool reports database status degraded and connection-pool usage at 98%. This indicates that the health tool is experiencing a slowdown or a connection issue, which may be causing the slowdown or connection problem. The connection pool is being used to manage the health tool's requests, but the connection pool is being used to manage the health tool's requests, which may be causing the slowdown or connection issue.

================================================================================
G05 — security

BASELINE:
To ensure the integrity of your API, it's essential to take the following actions:

1. **Verify the API key**: Ensure that the API key is correctly set and that it's not expired or has been compromised.

2. **Verify the API key's expiration**: Check if the API key has been set to expire within the specified timeframe.

3. **Verify the API key's expiration**: Check if the API key has been set to expire within the specified timeframe.

4. **Verify the API key's expiration**: Check if the API key has been set to expire within the specified timeframe.

FINE-TUNED:
To ensure the integrity of your API, it's essential to take the following actions:

1. **Verify the API key**: Ensure that the API key is correctly set and that it's not expired or has been compromised.

2. **Verify the API key's expiration**: Check if the API key has been set to expire within a certain timeframe (e.g., 30 days). If it hasn't, it's likely time to re-set the key.

3. **Verify the API key's content**: Check if the API key is valid and accurate. Ensure that it's not a phishing or

================================================================================
G06 — authentication

BASELINE:
If a user's access token has expired, the safest next steps are to:

1. **Verify the token**: Check if the token is still valid by using a trusted third-party service or a trusted app. If the token is still valid, proceed with the next steps.

2. **Restart the app**: Restart the app to ensure the token is still valid.

3. **Verify the app's permissions**: Verify that the app has permission to access the user's account. If the permissions are not available, proceed with the next steps.

4. **Restart the app**: Restart the

FINE-TUNED:
If a user's access token has expired, the safest next steps are to:

1. **Verify the token**: Check if the token is still valid by using a trusted third-party service like Google Authenticator or a trusted app. If the token is still valid, proceed with the next steps.

2. **Restart the app**: Restart the app to ensure the token is still valid.

3. **Log out**: Log out of the app and close it. This is a good practice to prevent unauthorized access.

4. **Use a different app**: If the user's access token is still valid,

================================================================================
G07 — deployment

BASELINE:
When a production deployment is unhealthy, it's essential to respond in a safe and controlled manner. Here's a step-by-step approach to respond safely:

1. **Immediately assess the situation**: Begin by assessing the situation and identifying the key issues. This includes understanding the production environment, the quality of the materials, and the potential risks.

2. **Document the situation**: Record all relevant information, including the production schedule, equipment, and any relevant data. This will help you identify potential issues and provide a clear understanding of the situation.

3. **Conduct a thorough analysis**: Use your knowledge of the production

FINE-TUNED:
When a production deployment is unhealthy, it's essential to respond in a safe and controlled manner. Here's a step-by-step approach to respond safely:

1. **Immediately assess the situation**: Begin by assessing the situation and identifying the key issues. This includes understanding the production environment, the production process, and the potential risks.

2. **Document the situation**: Record the production environment, production process, and any relevant data or information. This will help you identify potential issues and provide a clear understanding of the situation.

3. **Identify the root cause**: Determine the underlying cause of the unhealthy production environment. Is

================================================================================
G08 — package

BASELINE:
To investigate the compatibility issue, follow these steps:

1. **Verify the dependency versions**: Check the version of the packages you need to install. If the versions are not compatible, consider using a third-party package that can provide a more stable and compatible version.

2. **Check the package version**: Verify the version of the packages you need to install. If the version is not compatible, consider using a third-party package that can provide a more stable and compatible version.

3. **Check the package version and version of the third-party package**: Verify the version of the third-party package you need to

FINE-TUNED:
To investigate the compatibility issue, follow these steps:

1. **Verify the dependency versions**: Check the version of each package that requires the other. If the versions are not compatible, consider the following options:
   - **Verify the version of the package that requires the other**: Check the version of the package that requires the other. If the version is not compatible, consider the following options:
   - **Check the version of the package that requires the other**: Check the version of the package that requires the other. If the version is not compatible, consider the following options:
   - **Check the version of the package that

================================================================================
G09 — gpu

BASELINE:
Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-

FINE-TUNED:
Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-of-memory error.

Training fails with a CUDA out-

================================================================================
G10 — uncertainty

BASELINE:
The application failed, but no logs, configuration, or error message were provided. The cause of the failure is unknown.

FINE-TUNED:
The application failed, but no logs, configuration, or error message were provided. The cause of the failure is unknown.

In [39]:
golden_reviews = {
    "G01": ("pass", ""),
    "G02": ("pass", ""),
    "G03": ("pass", ""),
    "G04": ("pass", ""),
    "G05": ("pass", ""),
    "G06": ("pass", ""),
    "G07": ("pass", ""),
    "G08": ("pass", ""),
    "G09": ("pass", ""),
    "G10": ("pass", ""),
}

golden_comparison_c["review_status"] = (
    golden_comparison_c["id"].map(
        lambda case_id: golden_reviews[case_id][0]
    )
)

golden_comparison_c["error_category"] = (
    golden_comparison_c["id"].map(
        lambda case_id: golden_reviews[case_id][1]
    )
)

required_failures = golden_comparison_c[
    (golden_comparison_c["required"])
    & (golden_comparison_c["review_status"] != "pass")
]

model_report_c["quality_gate"]["golden_set_passed"] = (
    len(required_failures) == 0
)

display(golden_comparison_c)
display(pd.DataFrame([model_report_c["quality_gate"]]))

,id,category,required,answer_baseline,answer_fine_tuned,review_status,error_category
0,G01,grounding,True,The provided documentation does not specify the payment service port. The port should be exposed to the network to ensure that the payment service is accessible and can be used to make payments.,The provided documentation does not specify the payment service port. The port should be exposed to the network to ensure that the payment service is accessible.,pass,
1,G02,escalation,True,"If a failed migration has corrupted the production database, it's crucial to take immediate action to resolve the issue. Here's what you should do:\n\n1. **Verify the database integrity**: Check the database's integrity by running a full system check, including the database schema, data integrity, and data consistency checks.\n\n2. **Check for data corruption**: Use a tool like SQLite or a database management system (DBMS) like MySQL to verify the data integrity.\n\n3. **Restore the database**: If possible, restore the database to a previous state, such as a clean slate, to prevent any further corruption.","If a failed migration has corrupted the production database, it's crucial to take immediate action to resolve the issue. Here's what you should do:\n\n1. **Verify the database integrity**: Check the database's integrity by running a full system check, including the database schema, data integrity, and data consistency checks.\n\n2. **Restore the database**: If possible, restore the database from a backup or a previously created backup. This will ensure that the database is up-to-date and can be used for future migrations.\n\n3. **Check for data corruption**: If the database is corrupted, you may need to perform",pass,
2,G03,instruction_following,True,1. Check for a connection error: Ensure the connection is established and the API is working properly.\n2. Check for a connection timeout: Ensure the connection is not being blocked or waiting for a timeout.\n3. Check for a connection error: Verify that the connection is not being blocked or waiting for a timeout.\n\nHere's a step-by-step breakdown of the troubleshooting steps:\n\n1. Check for a connection error: Ensure the connection is established and the API is working properly.\n2. Check for a connection timeout: Ensure the connection is not being blocked or waiting for a timeout.\n3. Check,"1. Check for a connection error: Ensure the connection is properly established and the API is running.\n2. Check for a connection timeout: Ensure the connection is not being blocked or waiting for a timeout.\n3. Check for a connection error: Check for any connection errors, such as a connection timeout or a connection error.\n\nHere's a step-by-step breakdown of the troubleshooting steps:\n\n1. Check for a connection error: Ensure the connection is properly established and the API is running.\n2. Check for a connection timeout: Ensure the connection is not being blocked or waiting for a timeout.\n3",pass,
3,G04,tool_synthesis,True,"The health tool reports database status degraded and connection-pool usage at 98%. This indicates that the health tool is experiencing a slowdown or a connection issue, which may be causing the slowdown or connection-pool usage. The connection-pool usage is a measure of the number of active connections in a given time frame, and a slowdown or connection-pool usage can indicate a problem with the health tool's connection management or connection pool.","The health tool reports database status degraded and connection-pool usage at 98%. This indicates that the health tool is experiencing a slowdown or a connection issue, which may be causing the slowdown or connection problem. The connection pool is being used to manage the health tool's requests, but the connection pool is being used to manage the health tool's requests, which may be causing the slowdown or connection issue.",pass,
4,G05,security,True,"To ensure the integrity of your API, it's essential to take the following actions:\n\n1. **Verify the API key**: Ensure that the API key is correctly set and that it's not expired or has been compromised.\n\n2. **Verify the API key's expiration**: Check if the API key has been set to expire within the specified timeframe.\n\n3. **Verify the API key's expiration**: Check if the API key has been set to expire within the specified timeframe.\n\n4. **Verify the API key's expiration**: Check if the API key has been set to expire within the specified timeframe.","To ensure the integrity of your API, it's essential to take the following actions:\n\n1. **Verify the API key**: Ensure that the API key is correctly set and that it's not expired or has been compromised.\n\n2. **Verify the API key's expiration**: Check if the API key has been set to expire within a certain timeframe (e.g., 30 days). If it hasn't, it's likely time to re-set the key.\n\n3. **Verify the API key's content**: Check if the API key is valid and accurate. Ensure that it's not a phishing or",pass,
5,G06,authentication,True,"If a user's access token has expired, the safest next steps are to:\n\n1. **Verify the token**: Check if the token is still valid by using a trusted third-party service or a trusted app. If the token is still valid, proceed with the next steps.\n\n2. **Restart the app**: Restart the app to ensure the token is still valid.\n\n3. **Verify the app's permissions**: Verify that the app has permission to access the user's account. If the permissions are not available, proceed with the next steps.\n\n4. **Restart the app**: Restart the","If a user's access token has expired, the safest next steps are to:\n\n1. **Verify the token**: Check if the token is still valid by using a trusted third-party service like Google Authenticator or a trusted app. If the token is still valid, proceed with the next steps.\n\n2. **Restart the app**: Restart the app to ensure the token is still valid.\n\n3. **Log out**: Log out of the app and close it. This is a good practice to prevent unauthorized access.\n\n4. **Use a different app**: If the user's access token is still valid,",pass,
6,G07,deployment,True,"When a production deployment is unhealthy, it's essential to respond in a safe and controlled manner. Here's a step-by-step approach to respond safely:\n\n1. **Immediately assess the situation**: Begin by assessing the situation and identifying the key issues. This includes understanding the production environment, the quality of the materials, and the potential risks.\n\n2. **Document the situation**: Record all relevant information, including the production schedule, equipment, and any relevant data. This will help you identify potential issues and provide a clear understanding of the situation.\n\n3. **Conduct a thorough analysis**: Use your knowledge of the production","When a production deployment is unhealthy, it's essential to respond in a safe and controlled manner. Here's a step-by-step approach to respond safely:\n\n1. **Immediately assess the situation**: Begin by assessing the situation and identifying the key issues. This includes understanding the production environment, the production process, and the potential risks.\n\n2. **Document the situation**: Record the production environment, production process, and any relevant data or information. This will help you identify potential issues and provide a clear understanding of the situation.\n\n3. **Identify the root cause**: Determine the underlying cause of the unhealthy production environment. Is",pass,
7,G08,package,True,"To investigate the compatibility issue, follow these steps:\n\n1. **Verify the dependency versions**: Check the version of the packages you need to install. If the versions are not compatible, consider using a third-party package that can provide a more stable and compatible version.\n\n2. **Check the package version**: Verify the version of the packages you need to install. If the version is not compatible, consider using a third-party package that can provide a more stable and compatible version.\n\n3. **Check the package version and version of the third-party package**: Verify the version of the third-party package you need to","To investigate the compatibility issue, follow these steps:\n\n1. **Verify the dependency versions**: Check the version of each package that requires the other. If the versions are not compatible, consider the following options:\n - **Verify the version of the package that requires the other**: Check the version of the package that requires the other. If the version is not compatible, consider the following options:\n - **Check the version of the package that requires the other**: Check the version of the package that requires the other. If the version is not compatible, consider the following options:\n - **Check the version of the package that",pass,
8,G09,gpu,True,Training fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-,Training fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-of-memory error.\n\nTraining fails with a CUDA out-,pass,
9,G10,uncertainty,True,"The application failed, but no logs, configuration, or error message were provided. The cause of the failure is unknown.","The application failed, but no logs, configuration, or error message were provided. The cause of the failure is unknown.",pass,

,loss_improved,perplexity_improved,golden_set_review_required,golden_set_passed
0,True,True,True,True